data:
  image_dir: "local_data/image"
  mask_dir: "local_data/mask"
  size: 1024
  scales: [0.25, 1.0]
  split_ratio: 0.1

augment:
  bc_weak:
    brightness: 0.2
    contrast: 0.2
  bc_strong:
    brightness: 0.4
    contrast: 0.4

dl:
  batch: 1
  num_workers: 0
  pin_memory: false

train:
  max_lr: 1.0e-4
  min_lr: 1.0e-7
  warmup_steps: 50
  max_grad_norm: 1.0
  accum_steps: 1
  steps: 1000
  val_freq: 50
  save_freq: 100

loss:
  lambda_bce: 30.0
  lambda_iou: 0.5
  lambda_kl: 1.0
  lambda_aux: 1.0
